return PlaceObj('ModDef', {
	'title', "Martian Waters",
	'description', "Player-driven water creation for Surviving Mars Relaunched: carve rivers and lakes, flood the map into a sea, and control inflow, drainage, evaporation, and infiltration -- all built on the engine's TerrainWaterObject water grid.",
	'short_description', "Create rivers, lakes, and seas using the engine's water grid.",
	'id', "MartianWatersFA",
	'author', "fazevedo",
	'version', 3,
	'lua_revision', 350453,
	'saved_with_revision', 380799,
	'code', {
		"Code/mw_state.lua",
		"Code/mw_config.lua",
		"Code/mw_debug.lua",
		"Code/mw_textstyles.lua",
		"Code/mw_terrain.lua",
		"Code/mw_water.lua",
		"Code/mw_depth.lua",
		"Code/mw_flood.lua",
		"Code/mw_budget.lua",
		"Code/mw_sea.lua",
		"Code/mw_rain.lua",
		"Code/mw_clouds.lua",
		"Code/mw_api.lua",
		"Code/mw_tool.lua",
		"Code/mw_ui.lua",
		"Code/mw_lifecycle.lua",
		"Code/MartianWaters.lua",
	},
	'saved', 1780000000,
	'TagGameplay', true,
})
