return PlaceObj('ModDef', {
	'title', "Rivers",
	'description', "Player-driven river creation for Surviving Mars Relaunched. Carves bowl-shaped depressions along a path, then uses the engine's TerrainWaterObject system to fill them with water -- the terrain shapes the river.",
	'short_description', "Carve and fill big rivers using the engine's water grid.",
	'id', "RiversFA",
	'author', "fazevedo",
	'version', 1,
	'lua_revision', 350453,
	'saved_with_revision', 380799,
	'code', {
		"Code/r_version.lua",
		"Code/r_config.lua",
		"Code/r_debug.lua",
		"Code/r_terrain.lua",
		"Code/r_water.lua",
		"Code/r_api.lua",
		"Code/r_tool.lua",
		"Code/r_ui.lua",
		"Code/r_lifecycle.lua",
		"Code/Rivers.lua",
	},
	'saved', 1780000000,
	'TagGameplay', true,
})
