return PlaceObj('ModDef', {
	'title', "Mute Notifications",
	'description', "Selectively mute specific repeated Mission Control voice notifications (e.g. building/shuttle/drone spam) without lowering voice volume and without hiding any visual notifications. Adds 'Configure muted voice notifications...' under Game Options -> Audio, opening a searchable panel with a mute checkbox and a play/preview button per voiced notification.",
	'short_description', "Mute selected notifications",
	'image', "Mod/MuteNotifications/Images/final_composed.jpg",
	'last_changes', "Catalog: Comment selected POI and tutorial voices.",
	'id', "MuteNotifications",
	'author', "fredware",
	'version', 46,
	'lua_revision', 350453,
	'saved_with_revision', 392284,
	'code', {
		"Code/mn_config.lua",
		"Code/mn_debug.lua",
		"Code/mn_persistence.lua",
		"Code/mn_catalog.lua",
		"Code/mn_voice_suppression.lua",
		"Code/mn_panel.lua",
		"Code/mn_audio_options_patch.lua",
		"Code/MuteNotifications.lua",
	},
	'saved', 1780535068,
	'code_hash', -684951721204470755,
	'pdx_id', 146384,
	'pdx_version', "1",
	'TagGameplay', true,
})
