return PlaceObj('ModDef', {
	'title', "Mute Notifications",
	'description', "Selectively mute Mission Control alerts, HUD voices, tutorials, and scenario or mystery narration without lowering voice volume and without hiding any visual notifications. Adds 'Configure muted voice notifications...' under Game Options -> Audio, opening a searchable panel with a mute checkbox and a play/preview button for all verified recorded lines.",
	'short_description', "Mute selected notifications",
	'image', "Mod/MuteNotifications/Images/final_composed.jpg",
	'last_changes', "Fix the Steam release-build warning when catalog text contains context-dependent translation tags.",
	'id', "MuteNotifications",
	'author', "fredware",
	'version', 62,
	'lua_revision', 350453,
	'saved_with_revision', 405907,
	'code', {
		"Code/mn_config.lua",
		"Code/mn_debug.lua",
		"Code/mn_persistence.lua",
		"Code/mn_catalog.lua",
		"Code/mn_voice_suppression.lua",
		"Code/mn_panel.lua",
		"Code/mn_audio_options_patch.lua",
		"Code/MuteNotifications.lua",
	},
	'saved', 1790516007,
	'code_hash', -647177554191797657,
	'pdx_id', 146384,
	'pdx_version', "4",
	'steam_id', "3759765774",
	'TagGameplay', true,
})