return PlaceObj('ModDef', {
	'title', "Flexible Passages",
	'description', "Adds flexible dome passages: left-click to anchor the passage to a tile, and right-click to undo the last anchor point.\n\nInvalid placement (vanilla rules):\nBend is too sharp\nPassage is too long\nPassage is blocked by terrain, objects, or reserved space\n------------------------------------------------------------\n[IMPORTANT]: Quit and restart the game after enabling this mod to clear cached data.\nTested only on Surviving Mars Relaunched v1.0.7 on Windows 11.\nPlease complain! I can’t fix what I don’t know is broken. Anonymous feedback: https://smr-mods-feedback.fredware.app or github: https://github.com/facazevedo/surviving-mars-relaunched-mods/issues",
	'short_description', "Adds flexible dome passages",
	'image', "Mod/FlexiblePassages/Images/final_composed.jpg",
	'last_changes', "Debug logging is disabled by default.",
	'id', "FlexiblePassages",
	'author', "fredware",
	'version', 11,
	'lua_revision', 350453,
	'saved_with_revision', 396349,
	'code', {
		"Code/fp_version.lua",
		"Code/fp_config.lua",
		"Code/fp_debug.lua",
		"Code/fp_state.lua",
		"Code/fp_validation.lua",
		"Code/fp_construction_rules.lua",
		"Code/fp_lifecycle.lua",
		"Code/FlexiblePassages.lua",
	},
	'saved', 1782961392,
	'code_hash', -841050084844505724,
	'pdx_id', 146318,
	'pdx_version', "1",
	'steam_id', "3755970210",
	'TagGameplay', true,
})