return PlaceObj('ModDef', {
	'title', "Salvage tool shortcut",
	'description', "Press delete to toggle on/off salvage mode. \n\nFor bug reports and feature requests: https://github.com/facazevedo/surviving-mars-relaunched-mods/issues",
	'short_description', "Press Delete to toggle salvage mode.",
	'image', "Mod/SalvageToolShortcut/Images/final_composed.jpg",
	'id', "SalvageToolShortcut",
	'author', "fredware",
	'version', 4,
	'lua_revision', 350453,
	'saved_with_revision', 405907,
	'code', {
		"Code/sts_config.lua",
		"Code/sts_shortcuts.lua",
		"Code/SalvageToolShortcut.lua",
	},
	'saved', 1778976237,
	'code_hash', 5407875279216239418,
	'pdx_id', 144463,
	'pdx_version', "1",
	'TagInterface', true,
})
