return PlaceObj('ModDef', {
	'title', "T for tracks",
	'description', "Press t to toggle on/off train track placement mode. \n\nFor bug reports and feature requests: https://github.com/facazevedo/surviving-mars-relaunched-mods/issues",
	'short_description', "Press t to toggle train tracks.",
	'image', "Mod/TForTracks/Images/final_composed.jpg",
	'id', "TForTracks",
	'author', "fredware",
	'version', 4,
	'lua_revision', 350453,
	'saved_with_revision', 405907,
	'code', {
		"Code/tft_config.lua",
		"Code/tft_shortcuts.lua",
		"Code/TForTracks.lua",
	},
	'saved', 1778976375,
	'code_hash', 8283485458188130538,
	'pdx_id', 144465,
	'pdx_version', "1",
	'TagInterface', true,
})
