return PlaceObj('ModDef', {
	'title', "Disable All Mods",
	'description', "Disable and reenable every other active mod.",
	'short_description', "Disable and reenable every other active mod.",
	'image', "Mod/DisableAllMods/Images/final_composed_preview.jpg",
	'last_changes', "Adds the canonical ModTools item manifest and packages the publication assets in the mod payload.",
	'id', "DisableAllMods",
	'author', "fredware",
	'version', 12,
	'lua_revision', 350453,
	'saved_with_revision', 396349,
	'code', {
		"Code/dam_config.lua",
		"Code/dam_debug.lua",
		"Code/dam_state.lua",
		"Code/dam_mod_control.lua",
		"Code/dam_ui.lua",
		"Code/dam_disable_guard.lua",
		"Code/dam_lifecycle.lua",
		"Code/DisableAllMods.lua",
	},
	'saved', 1785474717,
	'code_hash', -4635904460384793834,
	'pdx_id', 153351,
	'pdx_version', "1",
	'steam_id', "3774857377",
	'TagInterface', true,
})