return PlaceObj('ModDef', {
	'title', "Force Delete",
	'description', "Press ctrl+delete to force-delete selected demolishable objects, such as bugged train tracks. \n\nFor bug reports and feature requests: https://github.com/facazevedo/surviving-mars-relaunched-mods/issues",
	'short_description', "Ctrl+Delete force-deletes the selected object.",
	'image', "Mod/ForceDelete/Images/force_delete.png",
	'id', "ForceDelete",
	'author', "fredware",
	'version', 4,
	'lua_revision', 350453,
	'saved_with_revision', 392284,
	'code', {
		"Code/ForceDelete.lua",
		"Code/fd_config.lua",
		"Code/fd_display_attributes.lua",
		"Code/fd_colonist.lua",
		"Code/fd_drone.lua",
		"Code/fd_animal.lua",
		"Code/fd_shuttle.lua",
		"Code/fd_deposit.lua",
		"Code/fd_infrastructure.lua",
		"Code/fd_internal_building.lua",
		"Code/fd_external_building.lua",
		"Code/fd_dome.lua",
	},
	'saved', 1778976137,
	'code_hash', 3373162618529736939,
	'pdx_id', 144462,
	'pdx_version', "1",
	'TagInterface', true,
})
